### ISSUE TITLE
Error : Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater

### ISSUE THREAD

**Issue by patrickroux** [mikelbring/tinyissue#142]
I have this error with 5.3.16 PHP version.

Unhandled Exception

Message:

Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater
Location:

Unknown on line 0

**Comment by tomerof** [comment]
I'm working with laravel 5 on php 5.6 with apache 2.4 and got this error.
sometimes it show it and sometimes it doesn't.
didn't find a solution yet.
