### ISSUE TITLE
Is this project dying?

### ISSUE THREAD

**Issue by Jamesking56** [mikelbring/tinyissue#213]
Hello,

I really like this project and want to use it on a Production basis... However, it seems as though there hasn't been a version update in 9 months. I don't want any software that isn't being updated on my server has it could become a security risk in the future.

Is this project dying or will there be updates released?

**Comment by satrun77** [comment]
I have updated the project to use Laravel 5. You can find the new alpha version here: https://github.com/satrun77/tinyissue

**Comment by woolfg** [comment]
cool!

**Comment by fnadde42** [comment]
There is a fork being maintained here
https://github.com/pixeline/bugs
