### ISSUE TITLE
Mysql config faulty after installation

### ISSUE THREAD

**Issue by simonlopez** [mikelbring/tinyissue#220]
We get this error after installation: SQLSTATE[HY000] [2005] Unknown MySQL server host '127.0.0.1:3306' (3)

This occurred at "app/laravel/database/connectors/mysql.php" on line 33.

To fix this, we need to edit config.app.php and change host config from:
'host'  => '127.0.0.1:3306'
to:
'host'  => '127.0.0.1;port=3306'

**Comment by Patriboom** [comment]
You can follow the fork [https://github.com/pixeline/bugs](https://github.com/pixeline/bugs)  which offers lot more options and capabilities.
