### ISSUE TITLE
cookie_session name conflict

### ISSUE THREAD

**Issue by vpakg** [mikelbring/tinyissue#221]
Just a suggestion. If running two Laravel application on the same server, and the cookie session have the same name + path, it will conflict. The user will be logged out of both applications. 

This can be solved by simply renaming the session_cookie or changing it's path. 

Path to the configuration should be : `tinyissue / app / application / config / session.php`

Assuming that the second laravel application is preserving the `laravel_session` name, it would be a good idea to have something like `tinyissue_session` instead.

**Comment by Patriboom** [comment]
Thanks.  I'll do that on my fork.
