### ISSUE TITLE
Tiny Issue > Bugs.

### ISSUE THREAD

**Issue by pixeline** [mikelbring/tinyissue#225]
Hello,

I love Tiny Issue and wanted to have many of the pull requests hanging there included. Therefore I forked the project and included many of the submitted pulls, into an opensource project that I called "Bugs". I use it daily with customers, and felt Bugs was more natural than "Tiny Issue" when communicating with them, hence the branding realignment.

Anyways, check it out at the project page: http://pixeline.github.io/bugs/

I'd be really happy if you want to contribute feedback, pull requests and send any issue over that you can find.

Happy debugging!
a.

**Comment by GerritHoekstra** [comment]
@pixeline @vpakg 

After roughly 2 days of working I've managed to convert the Bugs application from Laravel 3.1.4 to Laravel 4.2. You can find it in [this forked repository](https://github.com/GerritHoekstra/bugs). For the install guide see [here](https://github.com/GerritHoekstra/bugs#installing-bugs).

Changelog:
https://github.com/GerritHoekstra/bugs/blob/master/changes.md

Todo list:
https://github.com/GerritHoekstra/bugs/blob/master/TODO.MD

(A upgrade script is not yet provided for updating from v1.2)

**Comment by pixeline** [comment]
hi @GerritHoekstra, That sounds great.  I lack the time to thoroughly test your fork so it will have to wait the quieter days of July 2015 before being merged in the master.

**Comment by vpakg** [comment]
@GerritHoekstra thats great. I'm hoping to contribute somehow soon.

**Comment by GerritHoekstra** [comment]
@pixeline 
I'm looking forward to see this merged. You're welcome, I've converted this with pleasure for the purpose to learn more about object-oriented programming and Laravel itself.

@vpakg
I look forward to your contribution(s).

I've enabled issues tracking in the forked repository, If you find issues then let me know!

**Comment by JonWalkerTN** [comment]
This is really cool!  The only thing Tiny Issue is missing IMO is a simple time tracking component on tasks.  Are there any plans to implement something like this?  Thanks

**Comment by Patriboom** [comment]
Time tracking is included in the https://github.com/pixeline/bugs  version.
