### ISSUE TITLE
Parse error in the helpers.php (PHP version 5.6.3)

### ISSUE THREAD

**Issue by PaulEU** [mikelbring/tinyissue#227]
Parse error: syntax error, unexpected 'yield' (T_YIELD), expecting '(' in ..\tinyissue-master\app\laravel\helpers.php on line 563

**Comment by satrun77** [comment]
This is an issue with Laravel 3 as it is not compatible with PHP5.5 and above. From php5.5 'yield' is a reserved keyword. I have upgraded Tiny Issue to use Laravel 5. It is still working in progress, but most of the features are working fine. 

Repository: https://github.com/satrun77/tinyissue

**Comment by GerritHoekstra** [comment]
@satrun77 Great repository! Did you see [mine forked repository](https://github.com/GerritHoekstra/bugs)? It's based on Laravel 4.2.

Are you planning to convert all your layouts to [bootstrap](http://getbootstrap.com/)? If so, I've make a beginning with it in [this branch](https://github.com/GerritHoekstra/bugs/tree/bootstrap). (It's still based on Laravel 4.2 but I can try to fork your repository and make a bootstrap branch in that fork)

**Comment by satrun77** [comment]
Thanks @GerritHoekstra. Nice work on the migration to Laravel 4.2.

My fork is based on bootstrap that is included in Laravel 5. Forms and layout is bootstrap. Top navigation is not bootstrap.

My plan is to migrate:
- Everything in Tiny Issue v1.3.1 (Completed).
- All features that I have developed for v1.3.1. This includes:
    - Change issue project. (Completed)
    - Set default assignee.  (Completed)
    - Filter issue number is content into a url to the issue. (Completed)
    - Issue quote (Completed)
    - Project notes (Completed)
- Issue tags (Pull request from original repo).  (Completed)
- Add tests (codeception.com) (In progress)
- Setup build and automated test with Travis CI

**Comment by SkyzohKey** [comment]
To fix the issue in a simple way, just open `helpers.php` at line 563 and rename the `yeld` method to `_yeld`. :)
