### ISSUE TITLE
mcrypt_encrypt(): Size of key is too large for this algorithm

### ISSUE THREAD

**Issue by haryx8** [mikelbring/tinyissue#229]
get error when trying to create new issue

url:
http://[url]/project/1/issue/new

message:
Unhandled Exception

Message:

mcrypt_encrypt(): Size of key is too large for this algorithm
Location:

/apppath/tinyissue/app/laravel/crypter.php on line 40
Stack Trace:
#0 /apppath/tinyissue/app/laravel/laravel.php(42): Laravel\Error::native(2, 'mcrypt_encrypt(...', '/apppath/tiny...', 40)
#1 [internal function]: Laravel{closure}(2, 'mcrypt_encrypt(...', '/apppath/tiny...', 40, Array)
#2 /apppath/tinyissue/app/laravel/crypter.php(40): mcrypt_encrypt('rijndael-256', '59016017af6aafb...', '1\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F\x1F...', 'cbc', '\xBA8(\xEF0#~\xF0Lf,<\x0E\xC1h...')
#3 /apppath/tinyissue/app/laravel/view.php(386) : eval()'d code(48): Laravel\Crypter::encrypt(1)
#4 /apppath/tinyissue/app/laravel/view.php(386): eval()
#5 /apppath/tinyissue/app/laravel/view.php(353): Laravel\View->get()
#6 /apppath/tinyissue/app/laravel/view.php(447): Laravel\View->render()
#7 /apppath/tinyissue/app/laravel/view.php(372): Laravel\View->data()
#8 /apppath/tinyissue/app/laravel/view.php(353): Laravel\View->get()
#9 /apppath/tinyissue/app/laravel/view.php(590): Laravel\View->render()
#10 /apppath/tinyissue/app/laravel/response.php(246): Laravel\View->__toString()
#11 /apppath/tinyissue/app/laravel/laravel.php(180): Laravel\Response->render()
#12 /apppath/tinyissue/index.php(14): require('/apppath/tiny...')
#13 {main}

**Comment by marcelloinfoweb** [comment]
Estou com o mesmo problema com php 7.

**Comment by Patriboom** [comment]
Please visit the https://github.com/pixeline/bugs branch and upload the updates.
