### ISSUE TITLE
Magic_quotes error after header("Location: $url")

### ISSUE THREAD

**Issue by olikan** [mikelbring/tinyissue#231]
I hope someone has already the same problem

I'm using HybridAuth on my site. Everything worked great, but now it shows an error (Internal Server Error) in a popup window.

And error_log in hybridauth folder has a lot of messages

> PHP Fatal error:
> Directive 'magic_quotes_gpc' is no longer available in PHP in Unknown on line 0

Also I tried to catch the point where it caused and found that code worked perfect until Auth.php "`header('Location: $url')`".

**Comment by Patriboom** [comment]
Come and use https://github.com/pixeline/bugs instead.
So many changes have been made.  The fix you asked for, is only one small among so many we've corrected in the new version.
